spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
zuul:
  routes:
    service-hi:
      path: /service-hi/**/
      serviceId: service-hi
server:
  port: 8084